spring:
  application:
    name: numina-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    hikari:
      initialization-fail-timeout: -1
      connection-timeout: 30000
      validation-timeout: 5000
  jpa:
    show-sql: true
  flyway:
    locations: classpath:db/migration
    ignoreMigrationPatterns: repeatable:missing
    connect-retries: 10
    connect-retries-interval: 5s
